microservice:
  name: kotlin-spring-microservice
  image: alexanderbryksin/kotlin_spring_microservice:latest
  replicas: 1
  livenessProbe:
    httpGet:
      port: 8000
      path: /actuator/health/liveness
    initialDelaySeconds: 560
    periodSeconds: 5
  readinessProbe:
    httpGet:
      port: 8000
      path: /actuator/health/readiness
    initialDelaySeconds: 560
    periodSeconds: 5
  ports:
    http:
      name: http
      containerPort: 8000
  terminationGracePeriodSeconds: 30
  service:
    port: 8000